version: "3"

services:

  doab-postgres:
    image: postgres:11
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    ports:
      - "${DOAB_DB_PORT}:${DOAB_DB_PORT}"
    environment:
      - "POSTGRES_PASSWORD=${DOAB_DB_PASSWORD}"
      - "POSTGRES_USER=${DOAB_DB_USER}"
      - "POSTGRES_DB=${DOAB_DB_NAME}"

  doab-pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    environment:
      - "PGADMIN_DEFAULT_PASSWORD=${DOAB_DB_PASSWORD}"
      - PGADMIN_DEFAULT_EMAIL=doab@email.com
    ports:
      - "8080:80"

  doab:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    volumes:
      - ./volumes/out:/vol/out
      - ./doab/:/vol/app/doab
    environment:
      - DOAB_DB_PASSWORD
      - DOAB_DB_USER
      - DOAB_DB_HOST
      - DOAB_DB_NAME
      - DOAB_DEFAULT_OUT_DIR=/vol/out
    depends_on:
      - "start_dependencies"

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
     - "doab-postgres"
     - "doab-pgadmin"
    command: "doab-posrgres:${DOAB_DB_PORT}"
