"""
DOAB related constants
"""
from enum import Enum
import os
import re
from crossref.restful import Etiquette

# Search weights
MIN_TITLE_THRESHOLD = 0.25
MIN_AUTHOR_THRESHOLD = 1/2

CROSSREF_ETIQUETTE = Etiquette('Jisc DOAB Experiment', 'v1.0', 'https://www.jisc.ac.uk/rd/projects/open-metrics-lab',
                               'martin@eve.gd')


DOAB_URL = "https://www.doabooks.org"
DOAB_OAI_ENDPOINT = DOAB_URL + "/oai"

# https://www.crossref.org/blog/dois-and-matching-regular-expressions/
# 'for the 74.9M DOIs we have seen this matches 74.4M of them'
DOI_RE = re.compile(r"10.\d{4,9}/[-._;()/:A-Z0-9]+", re.IGNORECASE)

DEFAULT_OUT_DIR = os.getenv("DOAB_DEFAULT_OUT_DIR", "volumes/out")

RECOGNIZED_BOOK_TYPES = {
    'epub': 'book.epub',
    'pdf': 'book.pdf',
    'CambridgeCore': 'cc.html',
    'txt': 'citations.txt', # A file with all the extracted citations
}


#Parser Names:
ANYSTYLE = "Anystyle"
BLOOMSBURY_ACADEMIC = "Bloomsbury Academic"
CAMBRIDGE_CORE = "Cambridge Core"
CERMINE = "Cermine"
CROSSREF = "Crossref"
PALGRAVE_EPUB = "Palgrave Epub"


class Publisher(Enum):
    CAMBRIDGE_UNIVERSITY_PRESS = 1244
    SPRINGER = 1161
    OXFORD_UNIVERSITY_PRESS = 1210
    PALGRAVE_MACMILLAN = 1112
    BLOOMSBURY_ACADEMIC = 1131
    UBIQUITY_PRESS = 1194
    ACCADEMIA_UNIVERSITY_PRESS = 1474
    ALPARA = 1473
    CARRIERES_SOCIALES = 1508
    CASA_DE_VELAZQUEZ = 1464
    CEDEJ = 1463
    CEFAS = 1511
    CENTRAL_EUROPEAN_UNIVERSITY_PRESS = 1198
    CFE_ETHIOPIENNES = 1475
    CENTRE_JACQUES_BERQUE = 1461
    CENTRO_DE_ESTUDIOS_MEXICANOS = 1515
    CENTRO_DE_ESTUDIOS_INTERNACIONAIS = 1471
    CH_BECK = 1485
    CIDEHUS = 1499
    CNRS = 1297
    COLLEGE_DE_FRANCEA = 1199
    EDITIONS_CONTRECHAMPS = 1466
    BIBLIOTEQUE_NATIONALE_DE_FRANCE = 1675
    BIBLIOTEQUE_PUBLIQUE_INFORMATION = 1443
    EDITIONS_DE_LA_SORBONE = 1512
    ECOLE_DES_HAUTES_ETUDES_EN_SCIENCES_SOCIALES = 1525
    EDITIONS_DE_IHEAL = 1442
    EDIZIONI_KAPLAN = 1505
    ENS_EDITIONS = 1235
    GRADUATE_INSTITUTE_PUBLICATIONS = 1502
    INNSBRUCK_UNIVERSITY_PRESS = 1472
    INSTITUT_DE_LA_GESTION_PUBLIQUE = 1527
    IREMAM = 1520
    INSTITUTE_RECHERCHE_MAGHREB_CONTEMPORAIN = 1447
    IFRA_NIGERIA = 1517
    INSTITUTE_FRANCAIS_ETUDES_ANATOLIENNES = 1457
    INSTITUTE_FRANCAIS_ETUDES_ANDINES = 1510
    IRD_EDITIONS = 1470
    LEDIZIONI_LEDIPUBLISHING = 1201
    MOM_EDITIONS = 1688
    OPEN_EDITION_PRESS = 1147
    PRESSES_DE_IFPO = 1200
    PRESSES_DE_INALCO = 1528
    PRESSES_DE_UNIVERSITE_MONTREAL = 1355
    PRESSES_DES_MINES = 1503
    PRESSES_DE_SORBONNE_NOUVELLE = 1476
    PRESSES_AIX_MARSELLE = 1449
    PRESSES_UNIVERSITAIRES_CAEN = 1469
    PRESSES_UNIVERSITAIRES_MEDITERRANEE = 1507
    PRESSES_UNIVERSITAIRES_LIEGE = 1441
    PRESSES_UNIVERSITAIRES_LOUVAIN = 1456
    PRESSES_UNIVERSITAIRES_PARIS_NANTERRE = 1462
    PRESSES_UNIVERSITAIRES_PROVENCE = 1521
    PRESSES_UNIVERSITAIRES_RENNES = 1430
    PRESSES_UNIVERSITAIRES_SEPTENTRION = 1424
    PRESSES_UNIVERSITAIRES_FRANCOIS_RABELAIS = 1453
    PUBLICATIONS_CENTRE_JEAN_BERARD = 1482
    ROSENBERG_SELLIER = 1465
    SIGLO_DEL_HOMBRE_EDITORES = 1478
    SOCIETE_DES_OCEANISTES = 1506
    UGA_EDITIONS = 1467
    UNIVERSIDAD_EXTERNADO_COLOMBIA = 1501






