FROM python:3.7
RUN pip3 install psycopg2-binary
ADD scripts/* /usr/local/bin/
RUN chmod +x usr/local/bin/cermine
ADD lib/cermine.jar /usr/local/bin/cermine.jar
RUN apt update
RUN apt install -y openjdk-11-jdk-headless ruby ruby-dev
RUN gem install specific_install
RUN gem specific_install -l https://github.com/mauromsl/anystyle-cli.git

