"""Adds Tables

Revision ID: cd51caa7f650
Revises: a86948d64811
Create Date: 2019-07-04 21:15:28.651975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd51caa7f650'
down_revision = 'a86948d64811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('standarised_name', sa.String(), nullable=True),
    sa.Column('reference_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('doab_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('doab_id')
    )
    op.create_table('book_author',
    sa.Column('book_id', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.doab_id'], )
    )
    op.create_table('identifier',
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.doab_id'], ),
    sa.PrimaryKeyConstraint('value')
    )
    op.create_table('reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['referrer_id'], ['book.doab_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference')
    op.drop_table('identifier')
    op.drop_table('book_author')
    op.drop_table('book')
    op.drop_table('author')
    # ### end Alembic commands ###
